// Code generated by goctl. DO NOT EDIT!
// Source: rpcOrder.proto

package rpcorderclient

import (
	"context"

	"shop_mall/apps/order/rpcOrder/rpcOrder"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = rpcOrder.Request
	Response = rpcOrder.Response

	RpcOrder interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultRpcOrder struct {
		cli zrpc.Client
	}
)

func NewRpcOrder(cli zrpc.Client) RpcOrder {
	return &defaultRpcOrder{
		cli: cli,
	}
}

func (m *defaultRpcOrder) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := rpcOrder.NewRpcOrderClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
