// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.3
// source: rpcOrder.proto

package rpcOrder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RpcOrderClient is the client API for RpcOrder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcOrderClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type rpcOrderClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcOrderClient(cc grpc.ClientConnInterface) RpcOrderClient {
	return &rpcOrderClient{cc}
}

func (c *rpcOrderClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/rpcOrder.RpcOrder/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcOrderServer is the server API for RpcOrder service.
// All implementations must embed UnimplementedRpcOrderServer
// for forward compatibility
type RpcOrderServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedRpcOrderServer()
}

// UnimplementedRpcOrderServer must be embedded to have forward compatible implementations.
type UnimplementedRpcOrderServer struct {
}

func (UnimplementedRpcOrderServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRpcOrderServer) mustEmbedUnimplementedRpcOrderServer() {}

// UnsafeRpcOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcOrderServer will
// result in compilation errors.
type UnsafeRpcOrderServer interface {
	mustEmbedUnimplementedRpcOrderServer()
}

func RegisterRpcOrderServer(s grpc.ServiceRegistrar, srv RpcOrderServer) {
	s.RegisterService(&RpcOrder_ServiceDesc, srv)
}

func _RpcOrder_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcOrderServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcOrder.RpcOrder/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcOrderServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcOrder_ServiceDesc is the grpc.ServiceDesc for RpcOrder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcOrder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcOrder.RpcOrder",
	HandlerType: (*RpcOrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RpcOrder_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpcOrder.proto",
}
